### ISSUE TITLE
ERROR: PluginlibFactory 

### ISSUE THREAD

**Issue by xluo6688** [Fields2Cover/Fields2Cover#43]
Hello,

After installed the Fields2Cover ROS version (I am using Ubuntu 20.04) and run it with roslaunch fields2cover_ros view_field.launch
I got the following error. In RViz, the AerialMapDisplay is red which is not working. The demo.rviz is open but The /Visualizer cannot be opened as shown in your example. Would you please help me on the issue? Any instruction how to run the path planing?

 Thanks!

Best Regards,

```
wen@wen-ubuntu:~/catkin_ws/Fields2Cover$ roslaunch fields2cover_ros view_field.launch
... logging to /home/wen/.ros/log/624f0de4-8ab0-11ed-a91a-55903af4772a/roslaunch-wen-ubuntu-35234.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wen-ubuntu:37359/

SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.15.15
 * /visualizer/field_file: /home/wen/catkin_...

NODES
  /
    rqt_reconfigure (rqt_reconfigure/rqt_reconfigure)
    rviz (rviz/rviz)
    static_tf_fake (tf2_ros/static_transform_publisher)
    visualizer (fields2cover_ros/visualizer_node)

auto-starting new master
process[master]: started with pid [35253]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 624f0de4-8ab0-11ed-a91a-55903af4772a
process[rosout-1]: started with pid [35274]
started core service [/rosout]
process[visualizer-2]: started with pid [35277]
process[rviz-3]: started with pid [35281]
process[rqt_reconfigure-4]: started with pid [35283]
process[static_tf_fake-5]: started with pid [35284]

[ERROR] [1672672571.230346043]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: According to the loaded plugin descriptions the class rviz_plugins/AerialMapDisplay with base class type rviz::Display does not exist. Declared types are  rviz/AccelStamped rviz/Axes rviz/Camera rviz/DepthCloud rviz/Effort rviz/FluidPressure rviz/Grid rviz/GridCells rviz/Illuminance rviz/Image rviz/InteractiveMarkers rviz/LaserScan rviz/Map rviz/Marker rviz/MarkerArray rviz/Odometry rviz/Path rviz/PointCloud rviz/PointCloud2 rviz/PointStamped rviz/Polygon rviz/Pose rviz/PoseArray rviz/PoseWithCovariance rviz/Range rviz/RelativeHumidity rviz/RobotModel rviz/TF rviz/Temperature rviz/TwistStamped rviz/WrenchStamped rviz_plugin_tutorials/Imu
```

**Comment by Gonzalo-Mier** [comment]
Welcome @xluo6688!
The error appears because the package https://github.com/nobleo/rviz_satellite is not compiled in the same workspace as the fields2cover_ros package. If you run everything in local, the command `rosdep install -r --ignore-src -y --from-paths .` installs the rviz_satellite package automatically.  
I can see that you have a server on `http://wen-ubuntu:37359/`. I would say the problem can be solved cloning the rviz_satellite package the same workspace as fields2cover_ros.

PD: Next time, open issues related to the ROS package on its own page, please.

**Comment by xluo6688** [comment]
Thank you @Gonzalo-Mier for your response. I installed viz_satellite package into the work space: Fields2Cover, but after run with roslaunch fields2cover_ros view_field.launch, still got the same issue. Here is my work space: /catkin_ws/Fields2Cover/ Under this work space, there are these folds: build, build_isolated, devel, devel_isolated, rviz_satellite, src

It is really an amazing project. Any advice is appreciated!

**Comment by Gonzalo-Mier** [comment]
Rviz_satellite should be on the src folder, at the same level as fields2cover_ros. Then run `catkin_make_isolated`. Check if you have all the projects on the logs when doing the last command. Hope this solve the issue :)

**Comment by xluo6688** [comment]
Thanks @Gonzalo-Mier . Now installed Rviz_satellite in src fold. After run 
wen@wen-ubuntu:~/catkin_ws/Fields2Cover$ catkin_make_isolated

got the following error. 


[ 80%] Linking CXX executable /home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover_ros/lib/fields2cover_ros/visualizer_node
[100%] Built target visualizer_node
<== Finished processing package [2 of 3]: 'fields2cover_ros'

==> Processing catkin package: 'rviz_satellite'
==> Building with env: '/home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover_ros/env.sh'
==> cmake /home/wen/catkin_ws/Fields2Cover/src/rviz_satellite -DCATKIN_DEVEL_PREFIX=/home/wen/catkin_ws/Fields2Cover/devel_isolated/rviz_satellite -DCMAKE_INSTALL_PREFIX=/home/wen/catkin_ws/Fields2Cover/install_isolated -G Unix Makefiles in '/home/wen/catkin_ws/Fields2Cover/build_isolated/rviz_satellite'
-- Using CATKIN_DEVEL_PREFIX: /home/wen/catkin_ws/Fields2Cover/devel_isolated/rviz_satellite
-- Using CMAKE_PREFIX_PATH: /home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover_ros;/home/wen/catkin_ws/Fields2Cover/devel;/home/wen/catkin_ws/polygonCoverage_ws/devel;/opt/ros/noetic;/home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover
-- This workspace overlays: /home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover_ros;/home/wen/catkin_ws/Fields2Cover/devel;/home/wen/catkin_ws/polygonCoverage_ws/devel;/opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/wen/catkin_ws/Fields2Cover/build_isolated/rviz_satellite/test_results
-- Forcing gtest/gmock from source, though one was otherwise available.
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Using Python nosetests: /usr/bin/nosetests3
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at CMakeLists.txt:26 (find_package):
  By not providing "FindGeographicLib.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "GeographicLib", but CMake did not find one.

  Could not find a package configuration file provided by "GeographicLib"
  with any of the following names:

    GeographicLibConfig.cmake
    geographiclib-config.cmake

  Add the installation prefix of "GeographicLib" to CMAKE_PREFIX_PATH or set
  "GeographicLib_DIR" to a directory containing one of the above files.  If
  "GeographicLib" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/wen/catkin_ws/Fields2Cover/build_isolated/rviz_satellite/CMakeFiles/CMakeOutput.log".
See also "/home/wen/catkin_ws/Fields2Cover/build_isolated/rviz_satellite/CMakeFiles/CMakeError.log".
<== Failed to process package 'rviz_satellite': 
  Command '['/home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover_ros/env.sh', 'cmake', '/home/wen/catkin_ws/Fields2Cover/src/rviz_satellite', '-DCATKIN_DEVEL_PREFIX=/home/wen/catkin_ws/Fields2Cover/devel_isolated/rviz_satellite', '-DCMAKE_INSTALL_PREFIX=/home/wen/catkin_ws/Fields2Cover/install_isolated', '-G', 'Unix Makefiles']' returned non-zero exit status 1.

Reproduce this error by running:
==> cd /home/wen/catkin_ws/Fields2Cover/build_isolated/rviz_satellite && /home/wen/catkin_ws/Fields2Cover/devel_isolated/fields2cover_ros/env.sh cmake /home/wen/catkin_ws/Fields2Cover/src/rviz_satellite -DCATKIN_DEVEL_PREFIX=/home/wen/catkin_ws/Fields2Cover/devel_isolated/rviz_satellite -DCMAKE_INSTALL_PREFIX=/home/wen/catkin_ws/Fields2Cover/install_isolated -G 'Unix Makefiles'

Command failed, exiting.

**Comment by Gonzalo-Mier** [comment]
Those are dependency errors from the other package. They can be solved searching the error on Google and doing `apt install` to the appropriate package. Please, tell me if it works :)

**Comment by xluo6688** [comment]
Hello @Gonzalo-Mier, the dependency error is solved, Thanks. But when run "roslaunch fields2cover_ros view_field.launch", 

I got the following error message: 
'''[ERROR] [1673317219.495218299]: PluginlibFactory: The plugin for class 'rviz_plugins/AerialMapDisplay' failed to load.  Error: Could not find library corresponding to plugin rviz_plugins/AerialMapDisplay. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.'''

I cannot find the "plugin rviz_plugins/AerialMapDisplay"mentioned in the plugin_description.xml file

**Comment by Gonzalo-Mier** [comment]
The error is still that https://github.com/nobleo/rviz_satellite is not yet compiled/installed on your ROS system.

**Comment by xluo6688** [comment]
Thanks @Gonzalo-Mier . Yes, I need reboot my computer. Now it works

**Comment by Gonzalo-Mier** [comment]
Nice!! Enjoy it :)
